const GITHUB_MOCKUP_DATA = {
    "login": "dharm-2245832",
    "id": 171810707,
    "node_id": "U_kgDOCj2fkw",
    "avatar_url": "https://avatars.githubusercontent.com/u/171810707?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dharm-2245832",
    "html_url": "https://github.com/dharm-2245832",
    "followers_url": "https://api.github.com/users/dharm-2245832/followers",
    "following_url": "https://api.github.com/users/dharm-2245832/following{/other_user}",
    "gists_url": "https://api.github.com/users/dharm-2245832/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dharm-2245832/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dharm-2245832/subscriptions",
    "organizations_url": "https://api.github.com/users/dharm-2245832/orgs",
    "repos_url": "https://api.github.com/users/dharm-2245832/repos",
    "events_url": "https://api.github.com/users/dharm-2245832/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dharm-2245832/received_events",
    "type": "User",
    "site_admin": false,
    "name": "DHARM SINGH SAINI",
    "company": "NA",
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": "Hello! I'm DHARM from Jaipur, a B.Tech 3nd-year student and passionate frontend developer.",
    "twitter_username": null,
    "public_repos": 7,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2024-06-05T11:46:52Z",
    "updated_at": "2024-08-05T06:55:33Z"
}